//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbasesEntities : DbContext
    {
        public dbasesEntities()
            : base("name=dbasesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mesages> Mesages { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<News_category> News_category { get; set; }
        public virtual DbSet<News_images> News_images { get; set; }
        public virtual DbSet<News_subcategory> News_subcategory { get; set; }
        public virtual DbSet<News_videos> News_videos { get; set; }
        public virtual DbSet<Subscriber> Subscriber { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User_category> User_category { get; set; }
        public virtual DbSet<User_comment> User_comment { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
