//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News()
        {
            this.User_comment = new HashSet<User_comment>();
        }
    
        public int id { get; set; }
        public string longText { get; set; }
        public string shortText { get; set; }
        public System.DateTime add_date { get; set; }
        public int users_id { get; set; }
        public int category_id { get; set; }
        public Nullable<int> image_id { get; set; }
        public Nullable<int> video_id { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual News_category News_category { get; set; }
        public virtual News_images News_images { get; set; }
        public virtual News_videos News_videos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_comment> User_comment { get; set; }
    }
}
