//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_comment
    {
        public int id { get; set; }
        public string texts { get; set; }
        public int users_id { get; set; }
        public System.DateTime add_date { get; set; }
        public int news_id { get; set; }
    
        public virtual News News { get; set; }
        public virtual Users Users { get; set; }
    }
}
